### ISSUE TITLE
Planned 0.0.3-alpha changes

### ISSUE THREAD

**Issue by EliasRanz** [EliasRanz/AllianceCraft#2]
Feel free to add comments for other potential mods, and we will put it into consideration! Please provide a CurseForge link to the mod. It must be a **Forge** mod.

**This will be updated with changes requested, and checklist items will be completed once tested/verified on a dev server**

**New additions**

- [x] [Extreme sound muffler](https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler)
- [ ] [Chunk Loaders](https://www.curseforge.com/minecraft/mc-mods/chunk-loaders)
- [ ] [Just Another Mining Dimension](https://www.curseforge.com/minecraft/mc-mods/jamd)

**Removals**
- [x] FTB Chunks (replacing functionality with dedicated mods e.g. Chunk Loaders)
- [x] Better FPS (functionality managed by Optifine support)

**Client Side Removals**
- [x] Adaptive Performance Tweaks (Bundle)

**Maintenance**
- [x] Update mods to latest version
- [x] Add Documentation for Server Side only mods
- [ ] Cleanup Configs
- [x] Set `spawnNote = false` on `theoneprobe-common.toml`
- [x] Disable apotheosis book on spawn
- [x] Update Forge to 40.1.59

**Personal TODO**
- [x] Create a server only CurseForge instance and separate it Client vs Server. This will make exporting zip files easier.

**Comment by EliasRanz** [comment]
> Wanna add clean up config files for old mods that are not in the pack anymore and also possibly edit configs for mods.

Done

**Comment by mansrm81** [comment]
What configs do we wanna change?

**Comment by mansrm81** [comment]
We can get rid of better fps optifine overwrites that mod, also optifine does a better job when I tried it.

**Comment by EliasRanz** [comment]
> We can get rid of better fps optifine overwrites that mod, also optifine does a better job when I tried it.

Added `Better FPS` to list of removals. Also config changes not 100% on ATM. We haven't really dove much into mods at this point to identify what configs we might want to change, lol.

**Comment by mansrm81** [comment]
> > We can get rid of better fps optifine overwrites that mod, also optifine does a better job when I tried it.
> 
> Added `Better FPS` to list of removals. Also config changes not 100% on ATM. We haven't really dove much into mods at this point to identify what configs we might want to change, lol.

OK, that is what I was thinking also besides what we have changed so far for bug fixes.

**Comment by mansrm81** [comment]
Do you or would you want to add a dimension for mining for like the rftools builder quarry?

**Comment by mansrm81** [comment]
What about adding some sound mods there's a few out there but dunno which one you would like to use.

**Comment by EliasRanz** [comment]
Chunk loaders mod is no-go because it requires Forge 40.1.58 or above and we're on 40.1.57 lol

I'm also considering getting rid of the Vampirism mods, it would be cool to move to 1.19 at some point and those are only 1.18 mods.

**Comment by mansrm81** [comment]
> Chunk loaders mod is no-go because it requires Forge 40.1.58 or above and we're on 40.1.57 lol
> 
> I'm also considering getting rid of the Vampirism mods, it would be cool to move to 1.19 at some point and those are only 1.18 mods.

Yeah I'm fine with removing Vampirism from the pack and we can maybe replace it with something else? 1.19 optifine doesn't work unless you use a certain forge version just like 1.18.2 lol

**Comment by EliasRanz** [comment]
I'm gonna close this in favor of updating to 1.19 under #8
