### ISSUE TITLE
Receive OneProbe Book Every Login

### ISSUE THREAD

**Issue by EliasRanz** [EliasRanz/AllianceCraft#3]
When we login to the server we always get the OneProbe book

**Current workaround**
- Void them with the FTB Util trashcan or an alternative one.

**Possible solutions**
- Disable book in config (can we default oneprobe to be in the middle)

**Related Issues**
https://github.com/McJtyMods/TheOneProbe/issues/559

**Comment by EliasRanz** [comment]
Note: Jobs+ is being removed from the pack as part of #1

**Comment by mansrm81** [comment]
Using the /topcfg command you can (client side) reconfigure the position as well as the look of the probe information tooltip so we can disable the note.

**Comment by EliasRanz** [comment]
@mansrm81 do you know what property we need to change to disable the book?

**Comment by mansrm81** [comment]
config/theoneprobe-common.toml look for spawnNote = true change to false

**Comment by EliasRanz** [comment]
Modified this on the server, if we need to adjust this on the client then we can do manually for now, and will be addressed in #2
