### ISSUE TITLE
Door Issues

### ISSUE THREAD

**Issue by mansrm81** [EliasRanz/AllianceCraft#5]
Latest version of the pack

**Describe the bug**
Doors sometimes glitch out and opens half the door and sometimes it opens all the way and you can't go through. You have to open the door multiple times and aim towards the top hinge.

**To Reproduce**
1. Open door and try to go though the door way.
2. Doesn't matter what kind of door.
3. It doesn't always happen sometimes it works correctly.

**Screenshots**
I'll get one soon and update this post.

**Possible fix**
Might be Macaw's Doors mod.
*EDIT The mod might be FTB Chunks that is the issue with the doors.

**Comment by EliasRanz** [comment]
@mansrm81 If it's FTB Chunks the main functionality we're adding from that is chunk loading, so might be an alternative for that.

**Comment by EliasRanz** [comment]
I could potentially swap it with https://www.curseforge.com/minecraft/mc-mods/chunk-loaders to that functionality. The chunk claiming/protection is whatever.

**Comment by mansrm81** [comment]
> I could potentially swap it with https://www.curseforge.com/minecraft/mc-mods/chunk-loaders to that functionality. The chunk claiming/protection is whatever.

Yeah that looks good and change the total amount of chunks to something higher maybe double the size up to you.

**Comment by mansrm81** [comment]
> @mansrm81 If it's FTB Chunks the main functionality we're adding from that is chunk loading, so might be an alternative for that.

Yes once you claimed chunks is when it did it and so far on this world the claiming isn't having the problem we had last time when it removed me lol

**Comment by EliasRanz** [comment]
@mansrm81 yeah seems buggy, lol. I'll add Chunk Loaders to the pack for 0.0.3-alpha, which hopefully will resolve this issue.

**Comment by EliasRanz** [comment]
Given that we're restarting the pack for a 1.19 version I'm gonna close this and we can re-open if it's still an issue after doing #8
