### ISSUE TITLE
Villagers don't seem to spawn golems in an iron farm

### ISSUE THREAD

**Issue by EliasRanz** [EliasRanz/AllianceCraft#6]
**Pack Version:**
0.0.2-alpha

**Describe the bug**
When building an iron farm following the following tutorial the villagers don't spawn iron golems. 
https://www.youtube.com/watch?v=JxPhPR9SNvY

**Expected behavior**
Iron Golems should spawn in the top platform

**Screenshots**
![image](https://user-images.githubusercontent.com/1493142/181933466-072d3e81-1fbe-439e-8c97-cac4e10bd3ec.png)

**Additional context**
Villagers freak out, but they don't spawn a golem. Could be due to a mod that is conflicting with the functionality.

**Comment by EliasRanz** [comment]
I'm gonna aim to have this issue fixed in some capacity in #2. It could be a conflicting mod, or an addition of a new mod.

**Comment by EliasRanz** [comment]
So I tried a different tutorial and it seems to work 
https://www.youtube.com/watch?v=TRcRiymDP3U

![image](https://user-images.githubusercontent.com/1493142/182036599-646eca63-121e-4995-a63d-c18c82316d0d.png)
![image](https://user-images.githubusercontent.com/1493142/182036642-2e92a4da-8bfe-4166-9262-7afed6bca567.png)

**Comment by EliasRanz** [comment]
Can also use Create to do ore generation.

**Comment by mansrm81** [comment]
> Can also use Create to do ore generation.

Can also be used to automate food farms also.
