### ISSUE TITLE
AllianceCraft for 1.19

### ISSUE THREAD

**Issue by mansrm81** [EliasRanz/AllianceCraft#8]
# AliianceCraft for 1.19

I'm throwing together a pack for this and I'll try to get most if not all the mods in the 1.18.2 0.0.2 with some 0.0.3 changes mixed in.

# List of Mods
So far as mods go I have these shown in the image below.

![Screenshot 2022-08-04 110120](https://user-images.githubusercontent.com/8077454/182894191-cf043311-15a1-4117-92f0-2a895a02ec7d.png)

I will update this and I'll use some of your advise on what to add and remove from the pack.

**Comment by EliasRanz** [comment]
I would say let's keep it stupid basic and then iterate over it as we feel we need things.

**Comment by EliasRanz** [comment]
Create a base line and then build on top of that. This is the list I currently have

- Optifine
- Simple Storage Networks
- Angel Ring
- Comforts 
- Polymorph (avoids recipe conflicts as we add mods)
- Crafting tweaks
- Inventory tweaks
- Mouse tweaks
- Corpse (or alternate gravestone mod)
- AppleSkin
- JEI (+ addons)
- One Probe

**Features**
- Mining Dimension
- Quarry
- Chunk Loading (technically you can do Vanilla for this though)
- Core Tech mod (mekanism?)
- Core Magic mod (botania?)

I don't want to break vanilla mechanics e.g. vanilla farms and whatnot. I don't mind the vanilla experience, just want to enhance it and add additional content to enjoy.

**Comment by mansrm81** [comment]
Yeah I also wanna try and keep it small also with a little less mods that would be actually used and also not worry about some structures being generated also but with some dungeons for adventuring with an rpg style gameplay.

**Comment by mansrm81** [comment]
> Create a base line and then build on top of that. This is the list I currently have
> 
> **Features**
> 
> * Mining Dimension
> * Quarry
> * Chunk Loading (technically you can do Vanilla for this though)
> * Core Tech mod (mekanism?)
> * Core Magic mod (botania?)
> * Backpack mod
> * Fast travel mod (e.g. Waystones?)
> * Chest enhancements (e.g. Iron Chests, Storage Drawers, Better Barrels, or something along that line)
> * Make it easier to find items (e.g. Simple Storage Networks, ae2)
> * Exploration (so we don't feel like we should just stay at base, incentivize going out)
> * Gravestone mod of some sort (avoid despawning items because you die)
> * Item/Fluid transfer mod
> * Make inventory management easier (e.g. Inventory tweaks, mouse tweaks etc.)
> * Enhance crafting experience (e.g. crafting tweaks, polymorph, jei + addons)
> * Sleeping bags/sleep vote system (e.g. comforts)
> * End-game flight (e.g. Angel Rings)
> * Visualization of what items you're looking at (e.g. One Probe)
> * Better foods and visualization of saturation (e.g. AppleSkin)
> * Better performance (e.g. Optifine or equivalent)
> * Better building experience and options (Prefab for the lazy, and then furniture, roof, etc)
> 
> I don't want to break vanilla mechanics e.g. vanilla farms and whatnot. I don't mind the vanilla experience, just want to enhance it and add additional content to enjoy.

I'll make sure to add those that you have to what I have for my build.

**Comment by mansrm81** [comment]
Here is an updated list of mods that we have gathered so far.

![Screenshot 2022-08-05 132343](https://user-images.githubusercontent.com/8077454/183138480-f636d727-3f83-4573-a7cd-216ee1a3d20e.png)

**Comment by EliasRanz** [comment]
Uploaded current version to CurseForge and tagged it as 0.0.1. It does look like there might be a weird issue with Carry On/Project MMO interaction. I got into a position where I was stuck with Slowness 2, when I tried to carry a chest/furnace. I also couldn't place them down because it wasn't even rendering at all and let me keep picking stuff up and essentially voiding them.

**Comment by EliasRanz** [comment]
This is actually an issue with Inventory Profiles Next, requires changing config to disable the **Pick Items Directly into the Inventory**. It's under Locked Slots in the config.

**Comment by EliasRanz** [comment]
AllianceCraft 0.0.2 is here, going to close this issue now.
